---
apiVersion: v1
kind: Service
metadata:
  name: wealthwise
  namespace: wealthwise
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: wealthwise
  sessionAffinity: None
  type: ClusterIP
