---
kind: Secret
apiVersion: v1
metadata:
  name: financial-advisor-app-properties
  namespace: wealthwise
stringData:
  application.properties:
    quarkus.smallrye-health.root-path=/health
    quarkus.smallrye-health.liveness-path=liveness
    quarkus.smallrye-health.readiness-path=readiness
    quarkus.langchain4j.pgvector.dimension=1536
    quarkus.langchain4j.timeout=60s
    kafka.cloud-events=true
    mp.messaging.outgoing.wealthwise-history.connector=smallrye-kafka
    mp.messaging.outgoing.wealthwise-history.cloud-events-source=financial-advisor
    mp.messaging.outgoing.wealthwise-history.cloud-events-type=wealthwise-history
    mp.messaging.outgoing.wealthwise-history.cloud-events-subject=wealthwise-history
    mp.messaging.outgoing.wealthwise-history.cloud-events-mode=structured
type: Opaque

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: financial-advisor
  namespace: wealthwise
spec:
  template:
    spec:
      containers:
        - env:
            # NOTE: This CORS configuration is not safe and should only be used in Dev
            - name: QUARKUS_HTTP_CORS
              value: 'true'
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: '*'
            # This setting should point at the Kafka Bootstrap Server used to send
            # Kafka history events to the add-history function
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
          envFrom:
            - secretRef:
                name: openai-token
          image: 'quay.io/rh-ee-dwaters/ww-financial-advisor:latest'
          volumeMounts:
            - mountPath: /deployments/config
              name: config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: financial-advisor-app-properties
